#!/usr/bin/env bash
# Keep Foray sessions out of pm2's cgroup. Run by scripts/start.sh on every
# deploy; safe to run by hand. Idempotent. It only ever starts the unit;
# stopping or restarting it kills every session, so nothing here does that.
#
# 1. Generate foray-tmux.service for this account and checkout (User=,
#    HOME=, WorkingDirectory=, ExecStart= and the node PATH filled in from
#    the environment actually running this script — the same live-heredoc
#    idiom install.sh uses for the macOS LaunchAgent, not a separate
#    template file), plus the pm2 OOM drop-in and the needrestart
#    exclusion, when the rendered content differs from what's installed,
#    then start/enable the unit.
# 2. If a tmux server is running on Foray's socket outside that unit (e.g.
#    one Foray spawned under pm2 before the unit existed), move it and all
#    of its descendants into the unit's cgroup. cgroup v2 lets root re-home
#    live processes, so no session is disturbed. This never looks at any
#    socket but Foray's own — a stranger's own tmux server is never touched.
#
# On a box that still runs the legacy nest-tmux.service on the machine's
# default tmux socket, this script does nothing at all: see the guard below.

set -u
cd "$(dirname "$0")/.."

# --- leave a pre-rename box alone, before touching anything -----------
# A box that still has nest-tmux.service installed is holding live sessions
# on the machine's default socket, and they cannot be moved between tmux
# servers (docs/plans/foray-tmux-socket.md item 6). So do nothing at all
# here unless the caller has explicitly opted in by setting
# FORAY_TMUX_SOCKET to a non-empty name — which is the documented cutover
# step, taken by hand at a quiet moment.
#
# The test is ${FORAY_TMUX_SOCKET:-}, not ${FORAY_TMUX_SOCKET-foray}, so
# that *unset* counts as "not opted in" too. The pm2 config sets the
# variable to '' on such a box, but this script's own header invites
# running it by hand, and by hand there is no pm2 env: the socket would
# default to "foray" and this guard would wave the run through on exactly
# the machine it exists to protect.
#
# A fresh install has no legacy unit, so the second test fails and
# everything below proceeds normally.
if [ -z "${FORAY_TMUX_SOCKET:-}" ] && systemctl cat nest-tmux.service >/dev/null 2>&1; then
  echo "[tmux-unit] nest-tmux.service is installed; its sessions live on the default"
  echo "[tmux-unit] socket and cannot be moved. Leaving this box alone. To cut over,"
  echo "[tmux-unit] set FORAY_TMUX_SOCKET=foray once every session has been closed."
  exit 0
fi

SOCKET="${FORAY_TMUX_SOCKET-foray}"
SOCK=()
[ -n "$SOCKET" ] && SOCK=(-L "$SOCKET")
# Baked into the unit's own Environment=, below, so tmux-server.sh and the
# unit's ExecStop agree on the same socket across reboots, not just for the
# process that happened to install it.
SOCKET_FLAG=""
[ -n "$SOCKET" ] && SOCKET_FLAG="-L $SOCKET "

UNIT=foray-tmux.service
CGROUP=/sys/fs/cgroup/system.slice/$UNIT

install_if_changed() {
  local src="$1" dst="$2"
  if ! cmp -s "$src" "$dst"; then
    install -D -m 644 "$src" "$dst" && echo "[tmux-unit] installed $dst"
    return 0
  fi
  return 1
}

# Same idiom as the macOS LaunchAgent plist in install.sh: an unquoted
# heredoc that interpolates $VAR and $(cmd) live, rather than a static file
# plus sed substitution.
render_unit() {
  local node_bin here
  node_bin="$(dirname "$(command -v node)")"
  here="$(pwd)"
  cat <<UNIT
# $UNIT — generated by scripts/ensure-tmux-unit.sh, do not edit by hand.
#
# The tmux server that holds every Foray session, as its own systemd unit.
#
# Without this the server is spawned by Foray under pm2, so it lives in
# pm2's cgroup: a pm2 stop, or systemd tearing pm2 down after one of its
# processes is OOM-killed (2026-09-08: a Playwright Chrome), kills every
# session at once.
#
# scripts/tmux-server.sh runs the server in the foreground (\`tmux -D\`), so
# the unit has a live main process and its cgroup persists. A bare
# \`tmux start-server\` would daemonize and the oneshot cgroup would vanish.

[Unit]
Description=tmux server for Foray sessions
After=network.target
# Stopping or restarting kills every session. Refuse \`systemctl stop/restart\`
# (needrestart after an apt upgrade did that on 2026-09-09 06:10, and a
# session testing this setting did it again at 06:48 while the key sat in
# [Service], where systemd ignores it). Only a system shutdown may stop it.
# To really restart: remove this line, daemon-reload, restart, restore it.
RefuseManualStop=yes

[Service]
Type=simple
Restart=always
RestartSec=1
User=$(whoami)
Group=$(id -gn)
Environment=HOME=$HOME
Environment=SHELL=/bin/bash
Environment=LANG=en_US.UTF-8
Environment=PATH=$node_bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=FORAY_TMUX_SOCKET=$SOCKET
WorkingDirectory=$here
ExecStart=$here/scripts/tmux-server.sh
ExecStop=/usr/bin/tmux ${SOCKET_FLAG}kill-server
# One session's OOM-killed child must never stop this unit.
OOMPolicy=continue
# Prefer killing Foray/pm2 over a Claude session when memory runs out.
OOMScoreAdjust=-200
KillMode=control-group
LimitNOFILE=infinity
LimitNPROC=infinity

[Install]
WantedBy=multi-user.target
UNIT
}

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
render_unit > "$tmp"

changed=0
install_if_changed "$tmp" "/etc/systemd/system/$UNIT" && changed=1
install_if_changed scripts/systemd/pm2-oom-override.conf \
  "/etc/systemd/system/pm2-$(whoami).service.d/override.conf" && changed=1
# needrestart (run by unattended-upgrades) must never restart the unit.
install_if_changed scripts/systemd/needrestart-foray-tmux.conf \
  /etc/needrestart/conf.d/foray-tmux.conf
if [ "$changed" = 1 ]; then
  systemctl daemon-reload
  systemctl enable "$UNIT" >/dev/null 2>&1
fi
systemctl start "$UNIT" || { echo "[tmux-unit] could not start $UNIT" >&2; exit 1; }
# Type=simple returns before the server has its socket; give it a moment.
for _ in 1 2 3 4 5 6 7 8 9 10; do
  tmux "${SOCK[@]}" display-message -p '#{pid}' >/dev/null 2>&1 && break
  sleep 0.3
done

# Adopt a server that is running somewhere else — but only on Foray's own
# socket. The default socket may belong to someone else's tmux entirely and
# is never touched here.
server_pid=$(tmux "${SOCK[@]}" display-message -p '#{pid}' 2>/dev/null || true)
[ -n "$server_pid" ] || exit 0
current=$(cut -d: -f3 /proc/"$server_pid"/cgroup 2>/dev/null || true)
[ "$current" != "/system.slice/$UNIT" ] || exit 0

descendants() {
  local pid
  for pid in $(pgrep -P "$1"); do
    echo "$pid"
    descendants "$pid"
  done
}
moved=0
for pid in "$server_pid" $(descendants "$server_pid"); do
  if echo "$pid" > "$CGROUP/cgroup.procs" 2>/dev/null; then moved=$((moved + 1)); fi
done
echo "[tmux-unit] adopted tmux server $server_pid from $current ($moved processes)"
