#!/usr/bin/env bash
# ExecStart of foray-tmux.service (generated by scripts/ensure-tmux-unit.sh).
#
# Normally runs the tmux server in the foreground (`tmux -D`: no daemon,
# exit-empty off) so the unit owns it and its cgroup holds every session.
# Runs on Foray's own socket (FORAY_TMUX_SOCKET, default "foray"; empty
# means the machine's default socket, for a box installed before Foray had
# its own), with Foray's own config (scripts/foray.tmux.conf) — never
# ~/.tmux.conf.
#
# If a server is already up on that socket, one that the Foray app spawned
# under pm2 before this unit existed, we cannot start a second one. Instead
# hold the unit open while that server lives, so its cgroup exists for
# scripts/ensure-tmux-unit.sh to adopt the server into. When the old server
# finally exits, this script exits too and systemd restarts the unit, which
# then starts a fresh foreground server.

set -u

# Default socket: "foray" normally, but the machine's default socket on a
# box that still has the pre-rename unit installed. Its sessions live there
# and cannot be moved between tmux servers, so switching sockets would hide
# them and start a second, unprotected server. Detected rather than
# configured: an owner who forgets gets the safe answer. The same rule is
# in scripts/ensure-tmux-unit.sh and ecosystem.config.cjs — change all three
# together. Set FORAY_TMUX_SOCKET explicitly to override.
default_socket() {
  [ -f /etc/systemd/system/nest-tmux.service ] && echo "" || echo foray
}

SOCKET="${FORAY_TMUX_SOCKET-$(default_socket)}"
SOCK=()
[ -n "$SOCKET" ] && SOCK=(-L "$SOCKET")
CONF="$(cd "$(dirname "$0")" && pwd)/foray.tmux.conf"

pid=$(tmux "${SOCK[@]}" display-message -p '#{pid}' 2>/dev/null || true)
if [ -z "$pid" ]; then
  exec tmux "${SOCK[@]}" -f "$CONF" -D
fi
echo "[tmux-server] server $pid already running; holding the unit for it"
tmux "${SOCK[@]}" set -s exit-empty off
while kill -0 "$pid" 2>/dev/null; do sleep 15; done
echo "[tmux-server] server $pid exited"
